// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spfozvlfmlkqsdxudcko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwZm96dmxmbWxrcXNkeHVkY2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDM5MzksImV4cCI6MjA3MzYxOTkzOX0.fpDcFsr6lPsK_X5eXdTgAmVuyd3VbLDyWn6YTii5x4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});